feat: 문제 평가 전송 추가
Team-Questio/questio-api-server pull request #26
Opened 2024-08-17 08:34 UTC by hyeywon

### ✨ 작업 내용

- 생성된 문제에 대한 평가 전송 API 구현

---

### ✨ 참고 사항

- `.gitignore` 잘못 올림

---

### ⏰ 현재 버그

---

### ✏ Git Close

close #18

2024-08-17 09:10 UTC, sanghee0820 requested changes
수정 부탁드립니다.

추가로 Quest에 대한 FeedBack을 값이 아닌 Entity나, 값객체로 나누면 어떻게 생각하시나 여쭤봅니다.

2024-08-17 09:10 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/presentation/PortfolioController.java
> +    @PutMapping("/quest/{questId}")
PutMapping을 사용하신 이유가 있을까요??
리소스에 일부만 변경되어서 PatchMapping이 조금 더 적절하지 않을 까 싶긴합니다.

2024-08-17 09:10 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/domain/Quest.java
> +    }
feddBack이 Integer 값이면, 어느값이 긍정이고, 부정인지 확인할 수 없을 것 같네요.

Enum으로 값을 제한하는건 어떻게 생각하시는지 궁금합니다.

2024-08-17 09:10 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/presentation/PortfolioApiController.java
> +    ResponseEntity<Void> updateFeedback(Long questId, FeedbackRequest request);
여기에도 Swagger에 있는 @RequestBody()를 사용할 수 있습니다. 참고 한번 부탁드려요

2024-08-17 09:10 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/application/PortfolioFacadeService.java
> +    @Transactional
Transactional이 붙은 이유가 있을까요?

2024-08-17 09:10 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/application/QuestService.java
> +            .orElseThrow(() -> new IllegalArgumentException("Quest not found"));
CustomException으로 변경부탁드립니다.

2024-08-17 09:32 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/application/QuestService.java
>                  .toList();
스트림 사용하신거 좋네요

2024-08-17 17:02 UTC, doyooon reviewed
LGTM

2024-08-17 17:02 UTC, doyooon commented on src/main/java/team_questio/questio/portfolio/application/QuestService.java
> +            .orElseThrow(() -> new IllegalArgumentException("Quest not found"));
왜 NoSuchElementException 이 아니라 IllegalArgumentException 인가요? (진짜모름 진짜궁금)

2024-08-17 17:02 UTC, doyooon commented on src/main/java/team_questio/questio/portfolio/domain/Quest.java
> +    }
긍정 부정 두개라면 boolean으로 isGood 으로 처리하는 것도 간단할 것 같아요

2024-08-19 12:30 UTC, hyeywon commented on src/main/java/team_questio/questio/portfolio/domain/Quest.java
> +    }
아무 평가 없는 상태까지 포함해서 `GOOD`, `NONE`, `BAD` enum으로 변경했습니다.

2024-08-19 12:32 UTC, hyeywon commented on src/main/java/team_questio/questio/portfolio/application/QuestService.java
> +            .orElseThrow(() -> new IllegalArgumentException("Quest not found"));
통일하기 위해 작성해두었으나 custom exception으로 변경 완료하였습니다.

2024-08-19 13:09 UTC, hyeywon commented on src/main/java/team_questio/questio/portfolio/application/PortfolioFacadeService.java
> +    @Transactional
update가 끝나는 시점에 변경사항을 DB에 반영하기 위해서입니다.

2024-08-24 15:02 UTC, sanghee0820 approved these changes
LGTM

2024-08-24 15:02 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/domain/Quest.java
> +    private Integer feedback;
값객체로 바꾸는건 어떨까요?

2024-08-24 15:02 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/exception/PortfolioError.java
> +package team_questio.questio.portfolio.exception;
다른 곳 에서도 사용할 수 있으니 common -> exception으로 옮기는건 어떻게 생각하시나요?

2024-08-24 15:02 UTC, merged