Feat/40 portfolio constraint
Team-Questio/questio-api-server pull request #44
Opened 2024-08-27 08:56 UTC by hyeywon

### ✨ 작업 내용

포트폴리오 업로드 횟수 제한 기능 추가

---

### ✨ 참고 사항

최대 업로드 횟수에 대한 프로퍼티 값이 필요합니다.

.yaml
```yaml
portfolio:
  quota: 3
```
.properties
```properties
portfolio.quota=3
```

---

### ⏰ 현재 버그

---

### ✏ Git Close

close #40

2024-09-03 12:37 UTC, sanghee0820 requested changes
횟수를 증가시키는 것이 아닌, 차감하는 방식이 조금 더 좋아보입니다.

차감하는 방식으로 한다면, Quota 변수도 필요없게되고, 포트폴리오 생성 시 숫자 차감 후 0 이하면 오류 발생하는 식으로 하면 될 것 같습니다.

추가로, 남은 횟수를 반환해주는 API도 하나 있으면 좋을 것 같습니다.

2024-09-03 12:37 UTC, sanghee0820 commented on src/main/java/team_questio/questio/user/application/UserService.java
> +    private Integer quota;
총 횟수가 굳이 UserService에 없어도 될 듯 싶습니다.
User 생성 시 DefaultValue로 총 생성 가능 횟수를 설정한 후 차감하는 방식이 더 좋아보입니다.

2024-09-03 12:37 UTC, sanghee0820 commented on src/main/java/team_questio/questio/user/domain/User.java
> +    public Integer count(Integer quota) {
매서드 이름이 애매한 것 같습니다.

2024-09-03 12:37 UTC, sanghee0820 commented on src/main/java/team_questio/questio/portfolio/application/PortfolioFacadeService.java
> +        var remaining = userService.count(portfolioCommand.userId());
무엇을 카운트 하는지 애매한 것 같습니다.

2024-09-03 12:48 UTC, doyooon submitted a review, later dismissed
properties에 반영했습니다.

2024-09-03 13:18 UTC, hyeywon commented on src/main/java/team_questio/questio/user/application/UserService.java
> +    private Integer quota;
차감하는 방식으로 할 경우, User 생성 시 남은 횟수에 대한 기본값을 프로퍼티 파일에서 불러오는 방식이 불가능하여 횟수를 더하는 방식으로 했습니다. 다른 방법이 있을까요?

2024-09-03 13:24 UTC, hyeywon commented on src/main/java/team_questio/questio/user/domain/User.java
> +    public Integer count(Integer quota) {
수정했습니다. 피드백 부탁드립니다.

2024-09-03 13:25 UTC, hyeywon commented on src/main/java/team_questio/questio/portfolio/application/PortfolioFacadeService.java
> +        var remaining = userService.count(portfolioCommand.userId());
수정했습니다. 피드백 부탁드립니다.

2024-09-03 14:48 UTC, sanghee0820 commented on src/main/java/team_questio/questio/user/application/UserService.java
> +    private Integer quota;
굳이 프로퍼티 파일에서 기본값을 불러와야할 필요가 있을까 하는 의문이 듭니다. 혹시 이유를 알 수 있을까요?

2024-09-03 15:09 UTC, hyeywon commented on src/main/java/team_questio/questio/user/application/UserService.java
> +    private Integer quota;
하드코딩을 피하고자 프로퍼티 파일에서 불러오려고 했습니다.

2024-09-04 05:14 UTC, doyooon approved these changes
LGTM

2024-09-04 06:02 UTC, sanghee0820 approved these changes
프로퍼티스 관련해서는 한번 더 고민해보는걸로 하겠습니다.

2024-09-04 06:02 UTC, merged