잔여 횟수 조회 시 횟수 차감하는 오류 수정
Team-Questio/questio-api-server pull request #65
Opened 2024-09-07 04:53 UTC by hyeywon

### ✨ 작업 내용

ㅈㄱㄴ

---

### ✨ 참고 사항

---

### ⏰ 현재 버그

---

### ✏ Git Close

close #64

2024-09-08 14:34 UTC, doyooon submitted a review, later dismissed
Good

2024-09-09 07:07 UTC, sanghee0820 requested changes
간단히 가독성 부분과, 어노테이션 부분에서 리뷰남겼습니다 확인부탁드려요

2024-09-09 07:07 UTC, sanghee0820 commented on src/main/java/team_questio/questio/user/domain/User.java
>      @ColumnDefault("0")
이 부분 삭제해도 될 것 같습니다!

2024-09-09 07:07 UTC, sanghee0820 commented on src/main/java/team_questio/questio/user/persentation/UserController.java
> +            .body(RemainingResponse.of(userService.getQuota(id)));
userService에서 가져오는 부분과, response를 만드는 부분을 변수로 빼는것이 좋을 것 같습니다.

2024-09-09 13:21 UTC, sanghee0820 approved these changes
LGTM

2024-09-09 13:21 UTC, merged